name: Build and test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install numpy
        run: |
          conda install -c conda-forge numpy
      - name: Install
        run: pip install -v .
      - name: Test import
        run: python -c "import pygotm"
      - name: Clone gotm cases
        uses: actions/checkout@v4
        with:
          repository: gotm-model/cases
          path: cases
      - name: Run all test cases
        run: python .github/run_cases.py ./cases
